<?php

namespace Database\Seeders;

use App\Models\Operator;
use Illuminate\Database\Seeder;

class OperatorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $operators = [
            'KWI' => [
                "ADITYA ANANDA PUTRI PRATAMA",
                "AIDA NUR AVIDA",
                "AJI PAMUNGKAS",
                "AKHMAD ARIF PUJIONO",
                "ALIATUN NIKMAH",
                "ALIYAH NURUR ROKHIMAH",
                "ANAS TASYA PITRI A",
                "BAGUS SETIAWAN",
                "BUNGA VIKA KHARISMA",
                "CATRINE AMANDA BUDIARTI",
                "CHERIL VEBRI ANINDI",
                "DERIS SETIA DWI JULIAN",
                "DEVINA RAHMA",
                "DIANA LILIK JUWARNI",
                "DIFANI APRILIA BERLIANTI",
                "EGA NUR CAHYANA",
                "ELI SUSANTI",
                "ERIKO IFANDI",
                "FITA INDRIANI",
                "GITA AGUSTIN",
                "HANNA AYU PERTIWI",
                "HARUN AL RASYID",
                "HASAN MUKMIN ABDUNNASIR",
                "IMROATUL MUFIDAH",
                "INDRA SUNDARI",
                "IRDADIAN WAHYUNI",
                "KUSNUL AFIFA",
                "LINTANG DWIANING PUTRI",
                "LISTRIANA HENY",
                "LUMATUL ABIDAH",
                "LUTHFIYAH APTA INDRIATI",
                "M AGUNG SBASTIAN",
                "M FERI KURNIAWAN",
                "M NUR BAYU ANDRIANI PUTRA",
                "MAULANA RYAMZARD RYACUDU",
                "MIFTACHUN NIKMAH",
                "MILA INDAH CAHYANTI",
                "MOCHAMMAD RIZAL AINUR ROFIK",
                "MOH NUZULUL RAMADHANI",
                "MOHAMAD FARUL",
                "MUCHAMAD FAISAL ZAINUR ROZI",
                "MUHAMMAD ADE MAULANA",
                "MUHAMMAD ALI FAIZIN",
                "MUHAMMAD IMAM BAIHAKI KWI",
                "MUSONNINUR NISAK MEI",
                "NANI FITRIA",
                "NAWAF ADAMAZIZ",
                "NUR FAUZAN ROHMATULLOH",
                "PUTRI DIANA",
                "RIFKA AGUSTINA IFFAHYANTI",
                "RISKI ADI SETIAWAN",
                "RISTA  DWI PURWANTI",
                "RITA ARIYANTI",
                "ROHMATIN MAULIDA",
                "SEPTIAN ANDANI FAUZI",
                "SHABRINA ZULFIA RIZKA",
                "SINTA NOFITASARI",
                "SITI NURMA LIKATUS A.",
                "SRI WAHYUNI KWI",
                "SULTON ARIF",
                "SUPIYAH",
                "TRI AYU WILUJENG",
                "UMI FARIDA PUSPITA NINGRUM",
                "ZAINAL DINOVA",
                "MOCHAMAD SAIFUL AMIN",
                "ANGGUN CITRA LESTARI",
                "ANIS MUNTHOHIROH",
                "FIRMANUDIN YUGA PUTRA",
                "BILAL RAHMAD PANDEWO",
                "SINTA WANDARI",
                "SIROJUL ANWAR",
                "M ISKANDAR ALI",
                "RICO MORENO ARDIANSYAH",
                "FIRDHA NUR CAHYANI",
                "RENY HANAFIAH",
                "MOHAMMAD KHOIRUL HUDA",
                "YUSUF SANDI BIMAWAN",
                "ROBIATUL ADAWIYAH",
                "RINI HARIATI",
                "ILHAM KHOIRUN ABDILLAH",
                "MUHAMMAD DWIKY WAHYUDI",
                "IMROATUS SHOLIHAH",
                "NUR LAILATUL ROHMA",
                "NOVIANTI PARLIANDINI",
                "ABILIA SISKA SAPUTRI",
                "FRISKA SELYNA ASTIAJI",
                "KHARISMA MAHARANI PUTRI",
                "INDAH AYU PRATIWI",
                "YULIANA HERAWATI",
                "FANE SAFIORENTA PUTRI",
                "AL'AINA'UL MARDHIYAH",
                "AISYAH MAR'ATUN SHOLICHAH",
                "ALYA FITRI RHAMADHANI",
                "ACHMAD BAIEAD ABDILLA"
            ],
            'MJA' => [
                "AANG ABDULLOH SUKUR R",
                "ACHMAD EKO FIRMANDIANSYAH",
                "ADE NUR AINI",
                "ADEN IRGI HADIANTO",
                "AGUNG PRAYOGI",
                "AHMAD FAISAL",
                "AHMAD FAUZAN",
                "AKHMAD AKHIRU ZIKI ZAKARIA",
                "ALENA SABILLA LESTARI",
                "ALICIA PRENEPI Y",
                "AMELIA AZZAHRO",
                "ANTON HIDAYATUR ROKHIM",
                "APRILIA NUR CHAMIDAH",
                "ARIS DWI ARIANTO",
                "ARMAN ASHARI",
                "ATIK IRNAYATI",
                "AURA DIAS FAIZA",
                "CICAH MULYA FATMAWATI",
                "DAFFA AKTUR PRATAMA",
                "DAVID HADI PRASETYO",
                "DINI MEISYAROH",
                "DODIK IRFANUDIN",
                "EDO ISMAKA",
                "ELA ADELIA",
                "ELMA",
                "ELSA BUDI ARDHANIA",
                "ELY MULYANI",
                "FAISAL FAHRI",
                "FEBYMIA ARIFATUNASIKHA",
                "FENTI NOFITA SARI",
                "FIDIAN ARIS ANDIKA",
                "FIRDA ARIANTI",
                "HADI SUPRAYITNO",
                "HAMIDATUN NISA'",
                "HUSAIN JAUHARI ABDUL",
                "IDA PURWANTI",
                "IKA HANDAYANI",
                "ILMA RUFIANA",
                "ILMA SARI",
                "INAYATUL ULA",
                "INDAH ALISIA",
                "INDAH SULISTYORINI",
                "LULUK ROZAKOH",
                "LUSI NUR ANGGRANI",
                "M ALI BAIDHOWI",
                "M IKHSAN DAVID MAULANA",
                "M WILLIAM FARHANI",
                "MAY WIDIYA SAHARANI",
                "MOCHAMMAD SYAHRUL MUFARID",
                "MOHAMAD ANDI PRAYOGO",
                "MOHAMMAD NAUVAL",
                "MOKHAMAD ILHAM ZAKARIYA",
                "MUHAMMAD ANDY CHOIRUDIN",
                "MUHAMMAD DANANG SAPUTRA",
                "MUHAMMAD EFENDI",
                "MUHAMMAD SETIO MAULANA",
                "MUHHAMAD FADIL ALFIANTO",
                "MURTIANINGSIH",
                "NADIA NURDIANA PUTRI",
                "NADIA TASNIM",
                "NATASHYA SILVANIA ANDRIANA PUTRI",
                "NOVI EKA KUMALASARI",
                "NUR MANFAUNAH",
                "NURUL HASANAH",
                "NURUL KHATIMAH",
                "PRATIWI WIDYA SUSANTI",
                "PUTRI NOR FADHILAH",
                "QORRI AINA FATIMAH",
                "RADITYA ANGGA ANSORI",
                "RESTU BHAKTI HARTANTO",
                "REVA AMELIA PUTRI",
                "RINA LUSIANA",
                "ROHMATUL K",
                "ROZAQ GHANY AWALLUDIN",
                "RYAN ARI SETYAWAN",
                "SALVIA LESTARI",
                "SHINTA AYU LESTARI",
                "SITI NUR CHOLIZA",
                "SRI WULANDARI",
                "TIARA VIRZINIA",
                "TRI ILDA APRILIA",
                "VERA WIDYA WATI",
                "VIRA MEIDINA",
                "WAHYUNI RESTUNINGSIH",
                "WAHYU ADHY PRAJA",
                "REVA AMELIA PUTRI",
                "NADIN APRILIA PUTRI",
                "ANGGI HARYANTI",
                "HANI FAIZAH",
                "AMILIA PUTRI DEWI LISTYONO",
                "MOCHTAR ARIFIN",
                "ESTIA RINENGSEH",
                "TIRTA GIO RAMADHAN",
                "MUHAMMAD ZAINUL ARIFIN",
                "REVA MAULIDA",
                "APRILIA WULANDARI",
                "AHMAD AJI PRATAMA",
                "DWI AJENG ANGGRAINA",
                "ANGGUN KHALIMATUS SA'DIYAH",
                "ZELLO RIZKY ABIATI",
                "AHMAD RAFI FIVEDI ARIF",
                "SHOFIYATUS SA'ADAH",
                "YULIA ERLINA DEWI",
                "NANDA FAUZIA NURMALASARI",
                "RARA PUTRI IZZATUL ILMI",
                "LESTARI AYU NENGTIAS",
                "HAFIZH SUGARINAWATI",
                "MUSFIATI",
                "SHAHIRA AZULAIKA",
                "SINDA NEFIKA ARIANI"
            ],
            'AA' => [
                "AFISYA PARADISA",
                "ANDINDA SOFIATUR ROFICHO",
                "ANDRI ARDIANTO",
                "ARFIAN SAHRU R",
                "BUDI CAHYO TRI ATMOJO",
                "DEBI SETYAWAN",
                "DIENI NURUL KHAQQI EKA R",
                "FOURIZAL EKA FACHRUDIN",
                "HABIBATUL NUR INTAN",
                "HELMI RAFIF",
                "KASIH SEPTIA RAHMADANIA",
                "KHUSNUL KHOTIMAH BARU",
                "LYANA BUNGA PUTRI ARDITA",
                "M BAGUS MUHAIMIN",
                "MIA JULIANTI",
                "MOCH FELIX ALMAZ FAZAH",
                "MOCHAMMAD ADI PRAWIRO",
                "MOH. RUSDAN ROSYID",
                "MOHAMAD BIMA MA'ARIF",
                "MUHAMMAD ARBI SYAH NURIL",
                "MUHAMMNAD FARID NUR MAHFUDI",
                "NATALIA TRISTIN HAKIM",
                "NICKO BACHTIAR",
                "NUR ADINDA",
                "ONGKI WIDIANTO",
                "PASHA OKTAVIA",
                "RAGIL PRASETYO",
                "RETA PUTRI MEIDINA",
                "REZA ADITYA HILMY",
                "RISKA DWI SINTAWATI",
                "SALMAN AL FARISI",
                "SEPTIANSYAH ISWANTO",
                "SINTA AYU RISQI RAMADHANI",
                "WILDA JANUAR ASTIAJI",
                "YUSUF ARDIANSYAH",
                "SRI YANTI",
                "NURMALA HIDHAYANTI",
                "JUMAININGSIH",
                "KHOLIDAH KUSNIATIN",
                "MUHAMMAD YUSUF HANDI TIA",
                "DINA SABILA",
                "ELSATRI PUJIYATI",
                "LIA NOFITA SARI",
                "VIDA YULIATI",
                "KUSRINI",
                "ALFIN RIJKI",
                "ZHENI OKTA VIOLA",
                "MUHAMMAD AHWAN MUKAROM",
                "MUCHAMAD FAISAL NUL CKACKIM",
                "MUHAMMAD LEO BAGUS SATRIA",
                "M ARFIAN ARIF",
                "MIA ARI WIDYANINGRUM",
                "MOKHAMAD ABDULLAH BASOFI",
                "SRI WINDARTIK",
                "NAILATUS SA'ADAH",
                "AHMAD AINUR ROSYID",
                "ANGGUN SAFIRA",
                "ANIS NOFITASARI",
                "AMIROTUL MU'ALIMAH",
                "SRIS NOVITA EMILIAWATI",
                "YUDHA FATHUR RAHMA",
                "ANNISA SALSABILA",
                "IMA WILDATUS SHOLIKHAH",
                "NURUL ISTIQOMAH",
                "NADIRA ARIANTI",
                "NUR LAILI PERMATASARI",
                "GALANG YUWANA ARRAFI",
                "FERA HESTINA NATALIA",
                "DEWI EMALIA ANGGRAINI",
                "IMATUL JANNAH",
                "ARFINDA ZAHRA",
                "REZA NURAINI",
                "MILFA ARLIFI",
                "NUR HIDAYATUL AULIA",
                "CANTIKA ENDJELY",
                "SHOFY NAILATUL MUNAWAROH"
            ],
            'IPS' => [
                "ANNISA MAHAROTI ALFITRI",
                "DEA NUR RAHMA S",
                "EKA RAHAYU PUTRI A T",
                "FANDHI TRI SETYA",
                "FRINA FEBRIANI",
                "MILA NUR HIDAYAH",
                "NUR ROHMATIN",
                "RIDHO RISMAYA",
                "ROBIM JOSWANDA",
                "SELFIE RAMADHANI",
                "UYUN MASRUROH",
                "FILDZAHANAADITYA YONARA",
                "LULUK MUSFITA SARI",
                "KIKI AGUSTIN INTAVIS",
                "SASTA FADILA WARDANI",
                "FARADYA AMINATUZ  Z.",
                "ASMAUL HUSNAh",
                "MUHAMMAD DAFA WARDANA",
                "ETI SETYOWATI",
                "AYU SYAFRIDA",
                "GITARIA WIJIANTI",
                "MIFTAHUR ROHMAT AMIRUDDIN ZAKARIA",
                "NOVIA AGUSTINA",
                "MAUDIY PUTRI APRILLIA",
                "DARREL HYANGI MAHARANI",
                "LUTFI WULAN SARI",
                "SITI NUR ROHMAH",
                "DITA DWI ARIMBI",
                "NANANG WIJAYA",
                "HAFIS INDRA SAYOGA",
                "BAGUS DWI CAHYONO",
                "FERDIANSYAH PRAMUDYA",
                "MUHAMMAD ALFIRDAUS",
                "NANDHA AUDIA SLAMET",
                "MUHAMMAD LAZUARDI PRASETYO",
                "FIONANTA RAHMA ULA YUSTIAR",
                "AZZOYA PUTRI ASYARI",
                "FERNANDA APRILIA",
                "RIFQI ARIYANTO",
                "ARIS SULIANTO",
                "LAILATUL DWI ANISAH",
                "LAYLI NUR FITRIANA",
                "DEBY AMELIA",
                "RISDAYANTI ELVITA RANI",
                "NANIK FARIDA",
                "ERIKA",
                "CHURIL NUZULIATIL AFIFAH",
                "EKA RIWAYANTI NINGSIH",
                "SHEPTIA AYU FIRDAYANTI",
                "MARCELLA MARTA ABHINAYA",
                "ZILLA NUR ANGGRAINI",
                "FENY DWI ARIYANTI",
                "PUTRI WIDIANA",
                "SINTIA DARMA PUTRI",
                "SRI INDARWATI",
                "SYINBRAN FAJAR FATMA SARI",
                "FRISCA FEBY ANABELA",
                "AGUSTRIYA LESTARI",
                "SYARIFAH CHAMAMI",
                "IMAS PAMBAYU"
            ],
            'JMI' => [
                "ACKEMAD HARIANTO",
                "LIANA SISWANTI",
                "MUCHAMAD NUR AFANDI",
                "PANJI RAHMAT DARMAWAN"
            ]
        ];

        foreach ($operators as $vendor => $names) {
            foreach ($names as $name) {
                Operator::firstOrCreate([
                    'name' => $name,
                    'vendor' => $vendor
                ]);
            }
        }

        // Seed or update JMI Ella (Coordinator)
        Operator::updateOrCreate(
            ['name' => 'JMI Ella'],
            [
                'vendor' => 'JMI',
                'email' => 'panplt29@gmail.com',
                'role' => 'coordinator'
            ]
        );

        // Seed or update a staff operator for testing
        Operator::where('name', 'AIDA NUR AVIDA')->update([
            'email' => 'staff@example.com',
            'role' => 'karyawan'
        ]);
    }
}
